package com.somnus.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class MerAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.ACCT_ID
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Integer acctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.ACCT_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String acctCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.MER_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String merCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.ACCT_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String acctName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.CURRENCY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.BANK_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.BANK_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.BANK_KEY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String bankKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.BRANCH_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String branchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.BRANCH_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.BANK_ACCT_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String bankAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.BANK_ACCT_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String bankAcctName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.STL_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String stlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.BAL_FLOOR
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal balFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.AUTO_TRANSFER
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Integer autoTransfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.MIN_TRANSFER
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal minTransfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.TRANSFER_PERIOD
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String transferPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.IS_AUTO_STL
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String isAutoStl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.BEGIN_TRANSFER
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String beginTransfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.TRANSFER_PRIORITY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Integer transferPriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.ALLOW_IN
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String allowIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.ALLOW_OUT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String allowOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.OUT_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String outFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.REMARK
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.VERSION
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.OPER_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String operFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.EFFECT_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String effectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.LOSE_EFFECT_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String loseEffectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.MODIFY_BY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcim_mer_account.MODIFY_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.ACCT_ID
     *
     * @return the value of tcim_mer_account.ACCT_ID
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Integer getAcctId() {
        return acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.ACCT_ID
     *
     * @param acctId the value for tcim_mer_account.ACCT_ID
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAcctId(Integer acctId) {
        this.acctId = acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.ACCT_CODE
     *
     * @return the value of tcim_mer_account.ACCT_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getAcctCode() {
        return acctCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.ACCT_CODE
     *
     * @param acctCode the value for tcim_mer_account.ACCT_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAcctCode(String acctCode) {
        this.acctCode = acctCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.MER_CODE
     *
     * @return the value of tcim_mer_account.MER_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getMerCode() {
        return merCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.MER_CODE
     *
     * @param merCode the value for tcim_mer_account.MER_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setMerCode(String merCode) {
        this.merCode = merCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.ACCT_NAME
     *
     * @return the value of tcim_mer_account.ACCT_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getAcctName() {
        return acctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.ACCT_NAME
     *
     * @param acctName the value for tcim_mer_account.ACCT_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAcctName(String acctName) {
        this.acctName = acctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.CURRENCY
     *
     * @return the value of tcim_mer_account.CURRENCY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.CURRENCY
     *
     * @param currency the value for tcim_mer_account.CURRENCY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.BANK_CODE
     *
     * @return the value of tcim_mer_account.BANK_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.BANK_CODE
     *
     * @param bankCode the value for tcim_mer_account.BANK_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.BANK_NAME
     *
     * @return the value of tcim_mer_account.BANK_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.BANK_NAME
     *
     * @param bankName the value for tcim_mer_account.BANK_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.BANK_KEY
     *
     * @return the value of tcim_mer_account.BANK_KEY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBankKey() {
        return bankKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.BANK_KEY
     *
     * @param bankKey the value for tcim_mer_account.BANK_KEY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBankKey(String bankKey) {
        this.bankKey = bankKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.BRANCH_CODE
     *
     * @return the value of tcim_mer_account.BRANCH_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.BRANCH_CODE
     *
     * @param branchCode the value for tcim_mer_account.BRANCH_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.BRANCH_NAME
     *
     * @return the value of tcim_mer_account.BRANCH_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.BRANCH_NAME
     *
     * @param branchName the value for tcim_mer_account.BRANCH_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.BANK_ACCT_NO
     *
     * @return the value of tcim_mer_account.BANK_ACCT_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBankAcctNo() {
        return bankAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.BANK_ACCT_NO
     *
     * @param bankAcctNo the value for tcim_mer_account.BANK_ACCT_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBankAcctNo(String bankAcctNo) {
        this.bankAcctNo = bankAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.BANK_ACCT_NAME
     *
     * @return the value of tcim_mer_account.BANK_ACCT_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBankAcctName() {
        return bankAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.BANK_ACCT_NAME
     *
     * @param bankAcctName the value for tcim_mer_account.BANK_ACCT_NAME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBankAcctName(String bankAcctName) {
        this.bankAcctName = bankAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.STL_TYPE
     *
     * @return the value of tcim_mer_account.STL_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getStlType() {
        return stlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.STL_TYPE
     *
     * @param stlType the value for tcim_mer_account.STL_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setStlType(String stlType) {
        this.stlType = stlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.BAL_FLOOR
     *
     * @return the value of tcim_mer_account.BAL_FLOOR
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getBalFloor() {
        return balFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.BAL_FLOOR
     *
     * @param balFloor the value for tcim_mer_account.BAL_FLOOR
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBalFloor(BigDecimal balFloor) {
        this.balFloor = balFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.AUTO_TRANSFER
     *
     * @return the value of tcim_mer_account.AUTO_TRANSFER
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Integer getAutoTransfer() {
        return autoTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.AUTO_TRANSFER
     *
     * @param autoTransfer the value for tcim_mer_account.AUTO_TRANSFER
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAutoTransfer(Integer autoTransfer) {
        this.autoTransfer = autoTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.MIN_TRANSFER
     *
     * @return the value of tcim_mer_account.MIN_TRANSFER
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getMinTransfer() {
        return minTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.MIN_TRANSFER
     *
     * @param minTransfer the value for tcim_mer_account.MIN_TRANSFER
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setMinTransfer(BigDecimal minTransfer) {
        this.minTransfer = minTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.TRANSFER_PERIOD
     *
     * @return the value of tcim_mer_account.TRANSFER_PERIOD
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getTransferPeriod() {
        return transferPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.TRANSFER_PERIOD
     *
     * @param transferPeriod the value for tcim_mer_account.TRANSFER_PERIOD
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setTransferPeriod(String transferPeriod) {
        this.transferPeriod = transferPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.IS_AUTO_STL
     *
     * @return the value of tcim_mer_account.IS_AUTO_STL
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getIsAutoStl() {
        return isAutoStl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.IS_AUTO_STL
     *
     * @param isAutoStl the value for tcim_mer_account.IS_AUTO_STL
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setIsAutoStl(String isAutoStl) {
        this.isAutoStl = isAutoStl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.BEGIN_TRANSFER
     *
     * @return the value of tcim_mer_account.BEGIN_TRANSFER
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBeginTransfer() {
        return beginTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.BEGIN_TRANSFER
     *
     * @param beginTransfer the value for tcim_mer_account.BEGIN_TRANSFER
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBeginTransfer(String beginTransfer) {
        this.beginTransfer = beginTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.TRANSFER_PRIORITY
     *
     * @return the value of tcim_mer_account.TRANSFER_PRIORITY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Integer getTransferPriority() {
        return transferPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.TRANSFER_PRIORITY
     *
     * @param transferPriority the value for tcim_mer_account.TRANSFER_PRIORITY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setTransferPriority(Integer transferPriority) {
        this.transferPriority = transferPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.ALLOW_IN
     *
     * @return the value of tcim_mer_account.ALLOW_IN
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getAllowIn() {
        return allowIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.ALLOW_IN
     *
     * @param allowIn the value for tcim_mer_account.ALLOW_IN
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAllowIn(String allowIn) {
        this.allowIn = allowIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.ALLOW_OUT
     *
     * @return the value of tcim_mer_account.ALLOW_OUT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getAllowOut() {
        return allowOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.ALLOW_OUT
     *
     * @param allowOut the value for tcim_mer_account.ALLOW_OUT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAllowOut(String allowOut) {
        this.allowOut = allowOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.OUT_FLAG
     *
     * @return the value of tcim_mer_account.OUT_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getOutFlag() {
        return outFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.OUT_FLAG
     *
     * @param outFlag the value for tcim_mer_account.OUT_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setOutFlag(String outFlag) {
        this.outFlag = outFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.REMARK
     *
     * @return the value of tcim_mer_account.REMARK
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.REMARK
     *
     * @param remark the value for tcim_mer_account.REMARK
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.VERSION
     *
     * @return the value of tcim_mer_account.VERSION
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.VERSION
     *
     * @param version the value for tcim_mer_account.VERSION
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.STATUS
     *
     * @return the value of tcim_mer_account.STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.STATUS
     *
     * @param status the value for tcim_mer_account.STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.OPER_FLAG
     *
     * @return the value of tcim_mer_account.OPER_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getOperFlag() {
        return operFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.OPER_FLAG
     *
     * @param operFlag the value for tcim_mer_account.OPER_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setOperFlag(String operFlag) {
        this.operFlag = operFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.EFFECT_DATE
     *
     * @return the value of tcim_mer_account.EFFECT_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getEffectDate() {
        return effectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.EFFECT_DATE
     *
     * @param effectDate the value for tcim_mer_account.EFFECT_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setEffectDate(String effectDate) {
        this.effectDate = effectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.LOSE_EFFECT_DATE
     *
     * @return the value of tcim_mer_account.LOSE_EFFECT_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getLoseEffectDate() {
        return loseEffectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.LOSE_EFFECT_DATE
     *
     * @param loseEffectDate the value for tcim_mer_account.LOSE_EFFECT_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setLoseEffectDate(String loseEffectDate) {
        this.loseEffectDate = loseEffectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.MODIFY_BY
     *
     * @return the value of tcim_mer_account.MODIFY_BY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.MODIFY_BY
     *
     * @param modifyBy the value for tcim_mer_account.MODIFY_BY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcim_mer_account.MODIFY_TIME
     *
     * @return the value of tcim_mer_account.MODIFY_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcim_mer_account.MODIFY_TIME
     *
     * @param modifyTime the value for tcim_mer_account.MODIFY_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}