package com.somnus.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TrnTransaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.ACC_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String accTranNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.SYS_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String sysCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.MACHINE_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String machineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.CHANNEL_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String channelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.TERMINAL_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String terminalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.TRAN_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String tranCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.IPS_BILL_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String ipsBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.APP_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String appTranNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.APP_BATCH_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String appBatchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.CUS_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String cusTranNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.CHL_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String chlTranNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.PRD_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String prdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.TRAN_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String tranType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.INITIATOR_FLG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String initiatorFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.PAYEE_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String payeeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.PAYEE_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String payeeAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.PAYEE_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String payeeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.PAYEE_REL_SUB_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String payeeRelSubCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.PAYER_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String payerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.PAYER_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String payerAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.PAYER_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String payerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.PAYER_REL_SUB_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String payerRelSubCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.SUPPLIER_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.CHANNEL_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.CCY_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String ccyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.TRAN_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal tranAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.ORD_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal ordAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.IS_FEE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String isFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.FEE_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal feeAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.FEE_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.FEE_RATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal feeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.FEE_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String feeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.FEE_STL_MODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String feeStlMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.THIRD_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String thirdAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.REFUND_FEE_BK
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String refundFeeBk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.BANK_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String bankAccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.BANK_COST
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal bankCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.BANK_FEE_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String bankFeeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.BANK_FEE_RATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal bankFeeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.APP_TRAN_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Date appTranDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.SUBMIT_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Date submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.FINNISH_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Date finnishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.ACC_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Date accDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.IS_DEPOSIT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String isDeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.SECURITY_DEPOSIT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal securityDeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.DEPOSIT_REFUND_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Date depositRefundDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.DEPOSIT_STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String depositStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.RETURNED_DEPOSIT_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal returnedDepositAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.REFUNDED_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal refundedAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.DISHONORED_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private BigDecimal dishonoredAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.EST_ACC_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Date estAccTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.ACC_MODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String accMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.ACC_STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String accStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.FROZEN_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String frozenFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.BLN_MODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String blnMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.BLN_STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String blnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.CAN_BLN_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Date canBlnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.BLN_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private Date blnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.ERR_MSG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String errMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.VOUCHER_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String voucherNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.ORI_APP_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String oriAppTranNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.TRAN_REMARK
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String tranRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.RESV1
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String resv1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.RESV2
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String resv2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.RESV3
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String resv3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.RESV4
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String resv4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.RESV5
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String resv5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.CREATE_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.CREATE_BY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.MODIFY_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcor_trn_transaction.MODIFY_BY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    private String modifyBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.ACC_TRAN_NO
     *
     * @return the value of tcor_trn_transaction.ACC_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getAccTranNo() {
        return accTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.ACC_TRAN_NO
     *
     * @param accTranNo the value for tcor_trn_transaction.ACC_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAccTranNo(String accTranNo) {
        this.accTranNo = accTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.SYS_CODE
     *
     * @return the value of tcor_trn_transaction.SYS_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.SYS_CODE
     *
     * @param sysCode the value for tcor_trn_transaction.SYS_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.MACHINE_NO
     *
     * @return the value of tcor_trn_transaction.MACHINE_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getMachineNo() {
        return machineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.MACHINE_NO
     *
     * @param machineNo the value for tcor_trn_transaction.MACHINE_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setMachineNo(String machineNo) {
        this.machineNo = machineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.CHANNEL_NO
     *
     * @return the value of tcor_trn_transaction.CHANNEL_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.CHANNEL_NO
     *
     * @param channelNo the value for tcor_trn_transaction.CHANNEL_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setChannelNo(String channelNo) {
        this.channelNo = channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.TERMINAL_NO
     *
     * @return the value of tcor_trn_transaction.TERMINAL_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getTerminalNo() {
        return terminalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.TERMINAL_NO
     *
     * @param terminalNo the value for tcor_trn_transaction.TERMINAL_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setTerminalNo(String terminalNo) {
        this.terminalNo = terminalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.TRAN_CODE
     *
     * @return the value of tcor_trn_transaction.TRAN_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getTranCode() {
        return tranCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.TRAN_CODE
     *
     * @param tranCode the value for tcor_trn_transaction.TRAN_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setTranCode(String tranCode) {
        this.tranCode = tranCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.IPS_BILL_NO
     *
     * @return the value of tcor_trn_transaction.IPS_BILL_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getIpsBillNo() {
        return ipsBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.IPS_BILL_NO
     *
     * @param ipsBillNo the value for tcor_trn_transaction.IPS_BILL_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setIpsBillNo(String ipsBillNo) {
        this.ipsBillNo = ipsBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.APP_TRAN_NO
     *
     * @return the value of tcor_trn_transaction.APP_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getAppTranNo() {
        return appTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.APP_TRAN_NO
     *
     * @param appTranNo the value for tcor_trn_transaction.APP_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAppTranNo(String appTranNo) {
        this.appTranNo = appTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.APP_BATCH_NO
     *
     * @return the value of tcor_trn_transaction.APP_BATCH_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getAppBatchNo() {
        return appBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.APP_BATCH_NO
     *
     * @param appBatchNo the value for tcor_trn_transaction.APP_BATCH_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAppBatchNo(String appBatchNo) {
        this.appBatchNo = appBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.CUS_TRAN_NO
     *
     * @return the value of tcor_trn_transaction.CUS_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getCusTranNo() {
        return cusTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.CUS_TRAN_NO
     *
     * @param cusTranNo the value for tcor_trn_transaction.CUS_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setCusTranNo(String cusTranNo) {
        this.cusTranNo = cusTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.CHL_TRAN_NO
     *
     * @return the value of tcor_trn_transaction.CHL_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getChlTranNo() {
        return chlTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.CHL_TRAN_NO
     *
     * @param chlTranNo the value for tcor_trn_transaction.CHL_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setChlTranNo(String chlTranNo) {
        this.chlTranNo = chlTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.PRD_CODE
     *
     * @return the value of tcor_trn_transaction.PRD_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getPrdCode() {
        return prdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.PRD_CODE
     *
     * @param prdCode the value for tcor_trn_transaction.PRD_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setPrdCode(String prdCode) {
        this.prdCode = prdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.TRAN_TYPE
     *
     * @return the value of tcor_trn_transaction.TRAN_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getTranType() {
        return tranType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.TRAN_TYPE
     *
     * @param tranType the value for tcor_trn_transaction.TRAN_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setTranType(String tranType) {
        this.tranType = tranType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.INITIATOR_FLG
     *
     * @return the value of tcor_trn_transaction.INITIATOR_FLG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getInitiatorFlg() {
        return initiatorFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.INITIATOR_FLG
     *
     * @param initiatorFlg the value for tcor_trn_transaction.INITIATOR_FLG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setInitiatorFlg(String initiatorFlg) {
        this.initiatorFlg = initiatorFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.PAYEE_CODE
     *
     * @return the value of tcor_trn_transaction.PAYEE_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getPayeeCode() {
        return payeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.PAYEE_CODE
     *
     * @param payeeCode the value for tcor_trn_transaction.PAYEE_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setPayeeCode(String payeeCode) {
        this.payeeCode = payeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.PAYEE_ACC_CODE
     *
     * @return the value of tcor_trn_transaction.PAYEE_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getPayeeAccCode() {
        return payeeAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.PAYEE_ACC_CODE
     *
     * @param payeeAccCode the value for tcor_trn_transaction.PAYEE_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setPayeeAccCode(String payeeAccCode) {
        this.payeeAccCode = payeeAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.PAYEE_TYPE
     *
     * @return the value of tcor_trn_transaction.PAYEE_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getPayeeType() {
        return payeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.PAYEE_TYPE
     *
     * @param payeeType the value for tcor_trn_transaction.PAYEE_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setPayeeType(String payeeType) {
        this.payeeType = payeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.PAYEE_REL_SUB_CODE
     *
     * @return the value of tcor_trn_transaction.PAYEE_REL_SUB_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getPayeeRelSubCode() {
        return payeeRelSubCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.PAYEE_REL_SUB_CODE
     *
     * @param payeeRelSubCode the value for tcor_trn_transaction.PAYEE_REL_SUB_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setPayeeRelSubCode(String payeeRelSubCode) {
        this.payeeRelSubCode = payeeRelSubCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.PAYER_CODE
     *
     * @return the value of tcor_trn_transaction.PAYER_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getPayerCode() {
        return payerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.PAYER_CODE
     *
     * @param payerCode the value for tcor_trn_transaction.PAYER_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setPayerCode(String payerCode) {
        this.payerCode = payerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.PAYER_ACC_CODE
     *
     * @return the value of tcor_trn_transaction.PAYER_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getPayerAccCode() {
        return payerAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.PAYER_ACC_CODE
     *
     * @param payerAccCode the value for tcor_trn_transaction.PAYER_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setPayerAccCode(String payerAccCode) {
        this.payerAccCode = payerAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.PAYER_TYPE
     *
     * @return the value of tcor_trn_transaction.PAYER_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getPayerType() {
        return payerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.PAYER_TYPE
     *
     * @param payerType the value for tcor_trn_transaction.PAYER_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setPayerType(String payerType) {
        this.payerType = payerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.PAYER_REL_SUB_CODE
     *
     * @return the value of tcor_trn_transaction.PAYER_REL_SUB_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getPayerRelSubCode() {
        return payerRelSubCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.PAYER_REL_SUB_CODE
     *
     * @param payerRelSubCode the value for tcor_trn_transaction.PAYER_REL_SUB_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setPayerRelSubCode(String payerRelSubCode) {
        this.payerRelSubCode = payerRelSubCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.SUPPLIER_CODE
     *
     * @return the value of tcor_trn_transaction.SUPPLIER_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.SUPPLIER_CODE
     *
     * @param supplierCode the value for tcor_trn_transaction.SUPPLIER_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.CHANNEL_CODE
     *
     * @return the value of tcor_trn_transaction.CHANNEL_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.CHANNEL_CODE
     *
     * @param channelCode the value for tcor_trn_transaction.CHANNEL_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.CCY_CODE
     *
     * @return the value of tcor_trn_transaction.CCY_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getCcyCode() {
        return ccyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.CCY_CODE
     *
     * @param ccyCode the value for tcor_trn_transaction.CCY_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setCcyCode(String ccyCode) {
        this.ccyCode = ccyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.TRAN_AMT
     *
     * @return the value of tcor_trn_transaction.TRAN_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getTranAmt() {
        return tranAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.TRAN_AMT
     *
     * @param tranAmt the value for tcor_trn_transaction.TRAN_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setTranAmt(BigDecimal tranAmt) {
        this.tranAmt = tranAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.ORD_AMT
     *
     * @return the value of tcor_trn_transaction.ORD_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getOrdAmt() {
        return ordAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.ORD_AMT
     *
     * @param ordAmt the value for tcor_trn_transaction.ORD_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setOrdAmt(BigDecimal ordAmt) {
        this.ordAmt = ordAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.IS_FEE
     *
     * @return the value of tcor_trn_transaction.IS_FEE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getIsFee() {
        return isFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.IS_FEE
     *
     * @param isFee the value for tcor_trn_transaction.IS_FEE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setIsFee(String isFee) {
        this.isFee = isFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.FEE_AMT
     *
     * @return the value of tcor_trn_transaction.FEE_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getFeeAmt() {
        return feeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.FEE_AMT
     *
     * @param feeAmt the value for tcor_trn_transaction.FEE_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setFeeAmt(BigDecimal feeAmt) {
        this.feeAmt = feeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.FEE_TYPE
     *
     * @return the value of tcor_trn_transaction.FEE_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.FEE_TYPE
     *
     * @param feeType the value for tcor_trn_transaction.FEE_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.FEE_RATE
     *
     * @return the value of tcor_trn_transaction.FEE_RATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.FEE_RATE
     *
     * @param feeRate the value for tcor_trn_transaction.FEE_RATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.FEE_FLAG
     *
     * @return the value of tcor_trn_transaction.FEE_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getFeeFlag() {
        return feeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.FEE_FLAG
     *
     * @param feeFlag the value for tcor_trn_transaction.FEE_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setFeeFlag(String feeFlag) {
        this.feeFlag = feeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.FEE_STL_MODE
     *
     * @return the value of tcor_trn_transaction.FEE_STL_MODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getFeeStlMode() {
        return feeStlMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.FEE_STL_MODE
     *
     * @param feeStlMode the value for tcor_trn_transaction.FEE_STL_MODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setFeeStlMode(String feeStlMode) {
        this.feeStlMode = feeStlMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.THIRD_ACC_CODE
     *
     * @return the value of tcor_trn_transaction.THIRD_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getThirdAccCode() {
        return thirdAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.THIRD_ACC_CODE
     *
     * @param thirdAccCode the value for tcor_trn_transaction.THIRD_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setThirdAccCode(String thirdAccCode) {
        this.thirdAccCode = thirdAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.REFUND_FEE_BK
     *
     * @return the value of tcor_trn_transaction.REFUND_FEE_BK
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getRefundFeeBk() {
        return refundFeeBk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.REFUND_FEE_BK
     *
     * @param refundFeeBk the value for tcor_trn_transaction.REFUND_FEE_BK
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setRefundFeeBk(String refundFeeBk) {
        this.refundFeeBk = refundFeeBk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.BANK_ACC_CODE
     *
     * @return the value of tcor_trn_transaction.BANK_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBankAccCode() {
        return bankAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.BANK_ACC_CODE
     *
     * @param bankAccCode the value for tcor_trn_transaction.BANK_ACC_CODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBankAccCode(String bankAccCode) {
        this.bankAccCode = bankAccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.BANK_COST
     *
     * @return the value of tcor_trn_transaction.BANK_COST
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getBankCost() {
        return bankCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.BANK_COST
     *
     * @param bankCost the value for tcor_trn_transaction.BANK_COST
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBankCost(BigDecimal bankCost) {
        this.bankCost = bankCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.BANK_FEE_TYPE
     *
     * @return the value of tcor_trn_transaction.BANK_FEE_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBankFeeType() {
        return bankFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.BANK_FEE_TYPE
     *
     * @param bankFeeType the value for tcor_trn_transaction.BANK_FEE_TYPE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBankFeeType(String bankFeeType) {
        this.bankFeeType = bankFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.BANK_FEE_RATE
     *
     * @return the value of tcor_trn_transaction.BANK_FEE_RATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getBankFeeRate() {
        return bankFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.BANK_FEE_RATE
     *
     * @param bankFeeRate the value for tcor_trn_transaction.BANK_FEE_RATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBankFeeRate(BigDecimal bankFeeRate) {
        this.bankFeeRate = bankFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.APP_TRAN_DATE
     *
     * @return the value of tcor_trn_transaction.APP_TRAN_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Date getAppTranDate() {
        return appTranDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.APP_TRAN_DATE
     *
     * @param appTranDate the value for tcor_trn_transaction.APP_TRAN_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAppTranDate(Date appTranDate) {
        this.appTranDate = appTranDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.SUBMIT_TIME
     *
     * @return the value of tcor_trn_transaction.SUBMIT_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.SUBMIT_TIME
     *
     * @param submitTime the value for tcor_trn_transaction.SUBMIT_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.FINNISH_TIME
     *
     * @return the value of tcor_trn_transaction.FINNISH_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Date getFinnishTime() {
        return finnishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.FINNISH_TIME
     *
     * @param finnishTime the value for tcor_trn_transaction.FINNISH_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setFinnishTime(Date finnishTime) {
        this.finnishTime = finnishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.ACC_DATE
     *
     * @return the value of tcor_trn_transaction.ACC_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Date getAccDate() {
        return accDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.ACC_DATE
     *
     * @param accDate the value for tcor_trn_transaction.ACC_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAccDate(Date accDate) {
        this.accDate = accDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.IS_DEPOSIT
     *
     * @return the value of tcor_trn_transaction.IS_DEPOSIT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getIsDeposit() {
        return isDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.IS_DEPOSIT
     *
     * @param isDeposit the value for tcor_trn_transaction.IS_DEPOSIT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setIsDeposit(String isDeposit) {
        this.isDeposit = isDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.SECURITY_DEPOSIT
     *
     * @return the value of tcor_trn_transaction.SECURITY_DEPOSIT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getSecurityDeposit() {
        return securityDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.SECURITY_DEPOSIT
     *
     * @param securityDeposit the value for tcor_trn_transaction.SECURITY_DEPOSIT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setSecurityDeposit(BigDecimal securityDeposit) {
        this.securityDeposit = securityDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.DEPOSIT_REFUND_DATE
     *
     * @return the value of tcor_trn_transaction.DEPOSIT_REFUND_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Date getDepositRefundDate() {
        return depositRefundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.DEPOSIT_REFUND_DATE
     *
     * @param depositRefundDate the value for tcor_trn_transaction.DEPOSIT_REFUND_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setDepositRefundDate(Date depositRefundDate) {
        this.depositRefundDate = depositRefundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.DEPOSIT_STATUS
     *
     * @return the value of tcor_trn_transaction.DEPOSIT_STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getDepositStatus() {
        return depositStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.DEPOSIT_STATUS
     *
     * @param depositStatus the value for tcor_trn_transaction.DEPOSIT_STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setDepositStatus(String depositStatus) {
        this.depositStatus = depositStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.RETURNED_DEPOSIT_AMT
     *
     * @return the value of tcor_trn_transaction.RETURNED_DEPOSIT_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getReturnedDepositAmt() {
        return returnedDepositAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.RETURNED_DEPOSIT_AMT
     *
     * @param returnedDepositAmt the value for tcor_trn_transaction.RETURNED_DEPOSIT_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setReturnedDepositAmt(BigDecimal returnedDepositAmt) {
        this.returnedDepositAmt = returnedDepositAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.REFUNDED_AMT
     *
     * @return the value of tcor_trn_transaction.REFUNDED_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getRefundedAmt() {
        return refundedAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.REFUNDED_AMT
     *
     * @param refundedAmt the value for tcor_trn_transaction.REFUNDED_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setRefundedAmt(BigDecimal refundedAmt) {
        this.refundedAmt = refundedAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.DISHONORED_AMT
     *
     * @return the value of tcor_trn_transaction.DISHONORED_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public BigDecimal getDishonoredAmt() {
        return dishonoredAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.DISHONORED_AMT
     *
     * @param dishonoredAmt the value for tcor_trn_transaction.DISHONORED_AMT
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setDishonoredAmt(BigDecimal dishonoredAmt) {
        this.dishonoredAmt = dishonoredAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.EST_ACC_TIME
     *
     * @return the value of tcor_trn_transaction.EST_ACC_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Date getEstAccTime() {
        return estAccTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.EST_ACC_TIME
     *
     * @param estAccTime the value for tcor_trn_transaction.EST_ACC_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setEstAccTime(Date estAccTime) {
        this.estAccTime = estAccTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.ACC_MODE
     *
     * @return the value of tcor_trn_transaction.ACC_MODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getAccMode() {
        return accMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.ACC_MODE
     *
     * @param accMode the value for tcor_trn_transaction.ACC_MODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAccMode(String accMode) {
        this.accMode = accMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.ACC_STATUS
     *
     * @return the value of tcor_trn_transaction.ACC_STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getAccStatus() {
        return accStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.ACC_STATUS
     *
     * @param accStatus the value for tcor_trn_transaction.ACC_STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setAccStatus(String accStatus) {
        this.accStatus = accStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.FROZEN_FLAG
     *
     * @return the value of tcor_trn_transaction.FROZEN_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getFrozenFlag() {
        return frozenFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.FROZEN_FLAG
     *
     * @param frozenFlag the value for tcor_trn_transaction.FROZEN_FLAG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setFrozenFlag(String frozenFlag) {
        this.frozenFlag = frozenFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.STATUS
     *
     * @return the value of tcor_trn_transaction.STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.STATUS
     *
     * @param status the value for tcor_trn_transaction.STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.BLN_MODE
     *
     * @return the value of tcor_trn_transaction.BLN_MODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBlnMode() {
        return blnMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.BLN_MODE
     *
     * @param blnMode the value for tcor_trn_transaction.BLN_MODE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBlnMode(String blnMode) {
        this.blnMode = blnMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.BLN_STATUS
     *
     * @return the value of tcor_trn_transaction.BLN_STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getBlnStatus() {
        return blnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.BLN_STATUS
     *
     * @param blnStatus the value for tcor_trn_transaction.BLN_STATUS
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBlnStatus(String blnStatus) {
        this.blnStatus = blnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.CAN_BLN_DATE
     *
     * @return the value of tcor_trn_transaction.CAN_BLN_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Date getCanBlnDate() {
        return canBlnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.CAN_BLN_DATE
     *
     * @param canBlnDate the value for tcor_trn_transaction.CAN_BLN_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setCanBlnDate(Date canBlnDate) {
        this.canBlnDate = canBlnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.BLN_DATE
     *
     * @return the value of tcor_trn_transaction.BLN_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public Date getBlnDate() {
        return blnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.BLN_DATE
     *
     * @param blnDate the value for tcor_trn_transaction.BLN_DATE
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setBlnDate(Date blnDate) {
        this.blnDate = blnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.ERR_MSG
     *
     * @return the value of tcor_trn_transaction.ERR_MSG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.ERR_MSG
     *
     * @param errMsg the value for tcor_trn_transaction.ERR_MSG
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.VOUCHER_NO
     *
     * @return the value of tcor_trn_transaction.VOUCHER_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getVoucherNo() {
        return voucherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.VOUCHER_NO
     *
     * @param voucherNo the value for tcor_trn_transaction.VOUCHER_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.ORI_APP_TRAN_NO
     *
     * @return the value of tcor_trn_transaction.ORI_APP_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getOriAppTranNo() {
        return oriAppTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.ORI_APP_TRAN_NO
     *
     * @param oriAppTranNo the value for tcor_trn_transaction.ORI_APP_TRAN_NO
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setOriAppTranNo(String oriAppTranNo) {
        this.oriAppTranNo = oriAppTranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.TRAN_REMARK
     *
     * @return the value of tcor_trn_transaction.TRAN_REMARK
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getTranRemark() {
        return tranRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.TRAN_REMARK
     *
     * @param tranRemark the value for tcor_trn_transaction.TRAN_REMARK
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setTranRemark(String tranRemark) {
        this.tranRemark = tranRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.RESV1
     *
     * @return the value of tcor_trn_transaction.RESV1
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getResv1() {
        return resv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.RESV1
     *
     * @param resv1 the value for tcor_trn_transaction.RESV1
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setResv1(String resv1) {
        this.resv1 = resv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.RESV2
     *
     * @return the value of tcor_trn_transaction.RESV2
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getResv2() {
        return resv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.RESV2
     *
     * @param resv2 the value for tcor_trn_transaction.RESV2
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setResv2(String resv2) {
        this.resv2 = resv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.RESV3
     *
     * @return the value of tcor_trn_transaction.RESV3
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getResv3() {
        return resv3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.RESV3
     *
     * @param resv3 the value for tcor_trn_transaction.RESV3
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setResv3(String resv3) {
        this.resv3 = resv3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.RESV4
     *
     * @return the value of tcor_trn_transaction.RESV4
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getResv4() {
        return resv4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.RESV4
     *
     * @param resv4 the value for tcor_trn_transaction.RESV4
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setResv4(String resv4) {
        this.resv4 = resv4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.RESV5
     *
     * @return the value of tcor_trn_transaction.RESV5
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getResv5() {
        return resv5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.RESV5
     *
     * @param resv5 the value for tcor_trn_transaction.RESV5
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setResv5(String resv5) {
        this.resv5 = resv5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.CREATE_TIME
     *
     * @return the value of tcor_trn_transaction.CREATE_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.CREATE_TIME
     *
     * @param createTime the value for tcor_trn_transaction.CREATE_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.CREATE_BY
     *
     * @return the value of tcor_trn_transaction.CREATE_BY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.CREATE_BY
     *
     * @param createBy the value for tcor_trn_transaction.CREATE_BY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.MODIFY_TIME
     *
     * @return the value of tcor_trn_transaction.MODIFY_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.MODIFY_TIME
     *
     * @param modifyTime the value for tcor_trn_transaction.MODIFY_TIME
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcor_trn_transaction.MODIFY_BY
     *
     * @return the value of tcor_trn_transaction.MODIFY_BY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcor_trn_transaction.MODIFY_BY
     *
     * @param modifyBy the value for tcor_trn_transaction.MODIFY_BY
     *
     * @mbggenerated Tue Jun 02 21:34:51 CST 2015
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }
}